/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.AppController;
import Model.Librarian;
import javax.swing.*;
import java.awt.event.ActionEvent;
public class LibrarianView extends javax.swing.JFrame {
 private AppController appController;
    private Librarian currentLibrarian;
 
    public LibrarianView(AppController appController, Librarian librarian) {
        this.appController = appController;
        this.currentLibrarian = librarian;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Librarian Dashboard - " + librarian.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        adddelete = new javax.swing.JButton();
        issue = new javax.swing.JButton();
        ret = new javax.swing.JButton();
        LOUT = new javax.swing.JButton();
        vie = new javax.swing.JButton();
        VIB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("                 Librarian Section ");
        jLabel1.setOpaque(true);

        adddelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adddelete.setForeground(new java.awt.Color(0, 0, 255));
        adddelete.setText("Add/Delete Book");
        adddelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddeleteActionPerformed(evt);
            }
        });

        issue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        issue.setForeground(new java.awt.Color(51, 51, 255));
        issue.setText("Issue Book");
        issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueActionPerformed(evt);
            }
        });

        ret.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ret.setForeground(new java.awt.Color(0, 0, 255));
        ret.setText("Return Book");
        ret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retActionPerformed(evt);
            }
        });

        LOUT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LOUT.setForeground(new java.awt.Color(0, 0, 255));
        LOUT.setText("Logout");
        LOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOUTActionPerformed(evt);
            }
        });

        vie.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        vie.setForeground(new java.awt.Color(0, 0, 255));
        vie.setText("View Books");
        vie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vieActionPerformed(evt);
            }
        });

        VIB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        VIB.setForeground(new java.awt.Color(0, 0, 255));
        VIB.setText("View Issued Book");
        VIB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adddelete)
                    .addComponent(issue, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ret, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VIB, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(LOUT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adddelete, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vie, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(issue, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(VIB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ret, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vieActionPerformed
       ViewBooksView viewBooks = new ViewBooksView(appController);
        viewBooks.setVisible(true);
    }//GEN-LAST:event_vieActionPerformed

    private void adddeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddeleteActionPerformed
      ManageBookView manageBook = new ManageBookView(appController);
        manageBook.setVisible(true);
    }//GEN-LAST:event_adddeleteActionPerformed

    private void issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueActionPerformed
       IssueBookView issueView = new IssueBookView(appController, currentLibrarian);
        issueView.setVisible(true);
    }//GEN-LAST:event_issueActionPerformed

    private void retActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retActionPerformed
         ReturnBookView returnView = new ReturnBookView(appController, currentLibrarian);
        returnView.setVisible(true);
    }//GEN-LAST:event_retActionPerformed

    private void VIBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIBActionPerformed
        ViewIssuedBooksView viewIssued = new ViewIssuedBooksView(appController);
        viewIssued.setVisible(true);
    }//GEN-LAST:event_VIBActionPerformed

    private void LOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOUTActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to logout?", 
            "Confirm Logout", 
            JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose();
            WelcomeView welcome = new WelcomeView(appController);
            welcome.setVisible(true);
        }
    }//GEN-LAST:event_LOUTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         java.awt.EventQueue.invokeLater(() -> {
            AppController controller = new AppController();
            Librarian dummyLib = new Librarian("L001", "user", "pass", "Test User", "test@email.com", "1234567890");
            new LibrarianView(controller, dummyLib).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LOUT;
    private javax.swing.JButton VIB;
    private javax.swing.JButton adddelete;
    private javax.swing.JButton issue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton ret;
    private javax.swing.JButton vie;
    // End of variables declaration//GEN-END:variables
}
